namespace :tailwind do
  desc "Update Tailwind CSS source paths from Rails engines and main app"
  task update_source_paths: :environment do
    paths = Rails.application.config.tailwind_content_paths || []

    # Generate tailwind.config.js content
    config_content = <<~JS
      /** @type {import('tailwindcss').Config} */
      // This file is auto-generated by `rails tailwind:update_source_paths`
      // Do not edit manually - your changes will be overwritten
      // To add paths, register them in your engine's initializer or config/initializers/tailwind.rb
      export default {
        content: #{JSON.pretty_generate(paths)},
      }
    JS

    config_path = Rails.root.join('tailwind.config.js')
    File.write(config_path, config_content)

    puts "✓ Generated tailwind.config.js with #{paths.length} content paths"
    paths.each { |path| puts "  - #{path}" }
  end
end

# Hook into assets:precompile for production deployments
if Rake::Task.task_defined?("assets:precompile")
  Rake::Task["assets:precompile"].enhance(["tailwind:update_source_paths"])
end
